// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DelegationOrchestrationContext = { 
/**
 * Optional orchestration action type label.
 */
action_type: string | null, 
/**
 * Optional orchestration production type label.
 */
production_type: string | null, 
/**
 * Optional campaign identifier (`^[A-Z]+$`).
 */
campaign_id: string | null, 
/**
 * Optional phase identifier (`^\\d{2,}$`).
 */
phase_id: string | null, 
/**
 * Optional round identifier (`^[A-Za-z0-9._:-]{1,64}$`).
 */
round_id: string | null, 
/**
 * Optional step identifier (`^[A-Za-z0-9._:-]{1,64}$`).
 */
step_id: string | null, 
/**
 * Optional execution-lane label.
 */
execution_lane: string | null, };
