// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DelegationReport = { 
/**
 * High-level type of the delegated task.
 */
general_task_type: string, 
/**
 * Integer task difficulty on a 1 to 10 scale.
 */
task_difficulty_1_10: number, 
/**
 * Integer brief completeness on a 1 to 10 scale.
 */
brief_completeness_1_10: number, 
/**
 * Integer task self-sufficiency on a 1 to 10 scale.
 */
task_self_sufficiency_1_10: number, 
/**
 * Expected duration in whole minutes (minimum 1).
 */
expected_duration_minutes: number, 
/**
 * Why this agent should handle the task.
 */
why_this_agent: string, 
/**
 * Expected shape of the delivered output.
 */
expected_output_shape: string, 
/**
 * Files or scope the task should cover.
 */
files_or_scope: string, 
/**
 * Known risks or open questions.
 */
risks_or_unknowns: string, };
