// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MultiFileReaderItemStatus } from "./MultiFileReaderItemStatus";

export type MultiFileReaderEntry = { path: string, mode: string, startLine: number | null, endLine: number | null, lineCount: number | null, status: MultiFileReaderItemStatus, errorCode: string | null, };
