// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadRolloutAnalyzeResponse } from "./ThreadRolloutAnalyzeResponse";
import type { ThreadRolloutBackupInfo } from "./ThreadRolloutBackupInfo";

export type ThreadRolloutBackupRestoreResponse = { threadId: string, backup: ThreadRolloutBackupInfo, analysis: ThreadRolloutAnalyzeResponse, };
