// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionSource } from "./SessionSource";
import type { ThreadSessionAutoApplied } from "./ThreadSessionAutoApplied";
import type { ThreadSessionAutoDefaults } from "./ThreadSessionAutoDefaults";
import type { ThreadSessionAutoEffective } from "./ThreadSessionAutoEffective";

export type ThreadSessionAutoState = { threadName: string | null, sessionSource: SessionSource, loaded: boolean, configPath: string, statePath: string, version: string, isSubagent: boolean, defaults: ThreadSessionAutoDefaults, applied: ThreadSessionAutoApplied, effective: ThreadSessionAutoEffective, };
