// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadSessionAutoApplied = { enabled: boolean | null, autonomyLevel: bigint | null, autonomyStepPerRound: number | null, maxAutoRounds: bigint | null, doneStopScope: string | null, autoRounds: bigint, updatedAt: string | null, };
