// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadRolloutTrimPreview = { protectedHeadEndLine: bigint, requestedTailLines: number, requestedTailStartLine: bigint, actualTailStartLine: bigint, preservedTailLines: bigint, removedMiddleStartLine: bigint | null, removedMiddleEndLine: bigint | null, removedMiddleLines: bigint, estimatedRemovedBytes: bigint, compactionAnchorLine: bigint | null, };
