// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NeroAutoRuntimeConfig } from "../NeroAutoRuntimeConfig";

export type ThreadSessionAutoEffective = { runtime: NeroAutoRuntimeConfig, autonomyStepPerRound: number, doneStopScope: string, autoRounds: bigint, source: string, };
