// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionSource } from "./SessionSource";
import type { ThreadRolloutBackupInfo } from "./ThreadRolloutBackupInfo";
import type { ThreadRolloutStats } from "./ThreadRolloutStats";
import type { ThreadRolloutTrimPreview } from "./ThreadRolloutTrimPreview";

export type ThreadRolloutAnalyzeResponse = { threadId: string, threadName: string | null, rolloutPath: string | null, archived: boolean, source: SessionSource | null, forkedFromId: string | null, isSubagent: boolean, loaded: boolean, eligible: boolean, blockers: Array<string>, warnings: Array<string>, stats: ThreadRolloutStats | null, trim: ThreadRolloutTrimPreview | null, analysisFingerprint: string | null, backup: ThreadRolloutBackupInfo | null, };
