// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NeroAutoRuntimeConfig } from "../NeroAutoRuntimeConfig";

export type ThreadSessionAutoUpdateParams = { threadId: string, expectedVersion: string, runtime: NeroAutoRuntimeConfig, autonomyStepPerRound?: number | null, doneStopScope?: string | null, resetCounter?: boolean, };
