// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionSource } from "./SessionSource";

export type ThreadSessionAutoUpdateParams = { threadId: string, expectedVersion: string, expectedSessionSource?: SessionSource | null, enabled?: boolean | null, autonomyLevel?: number | null, autonomyStepPerRound?: number | null, maxAutoRounds?: number | null, doneStopScope?: string | null, autoRounds?: number | null, resetCounter?: boolean, };
