// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadSessionAutoAuthorityMode } from "./ThreadSessionAutoAuthorityMode";
import type { ThreadSessionAutoState } from "./ThreadSessionAutoState";

export type ThreadSessionAutoUpdateResponse = { threadId: string, authority: ThreadSessionAutoAuthorityMode, applied: boolean, conflict: boolean, message: string | null, state: ThreadSessionAutoState | null, };
