// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadSessionAutoAuthorityMode } from "./ThreadSessionAutoAuthorityMode";
import type { ThreadSessionAutoState } from "./ThreadSessionAutoState";

export type ThreadSessionAutoReadResponse = { threadId: string, authority: ThreadSessionAutoAuthorityMode, state: ThreadSessionAutoState, };
