// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadRolloutBackupInfo = { backupRoot: string, manifestPath: string, backupRolloutPath: string, originalRolloutPath: string, createdAt: string, originalTotalLines: bigint, originalTotalBytes: bigint, trimmedTotalLines: bigint, trimmedTotalBytes: bigint, protectedHeadEndLine: bigint, requestedTailLines: number, actualTailStartLine: bigint, analysisFingerprint: string, };
