// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpawnContextInheritanceSuppressionReason } from "./SpawnContextInheritanceSuppressionReason";

export type SpawnContextInheritanceTelemetry = { 
/**
 * Replay-safe parent turn count observed before trimming.
 */
parent_replay_safe_turn_count: number | null, 
/**
 * Replay-safe turn count shipped into the child fork payload.
 */
shipped_replay_safe_turn_count: number | null, 
/**
 * Approximate token count of the shipped candidate payload.
 */
estimated_shipped_tokens: bigint | null, 
/**
 * Practical child startup budget proxy used during bounded evaluation.
 */
usable_context_budget_tokens: bigint | null, 
/**
 * Explicit reason when requested inheritance was suppressed or downgraded.
 */
suppression_reason: SpawnContextInheritanceSuppressionReason | null, };
